/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import PatientManagementSystem.Accounts.Admin;
import PatientManagementSystem.Login.AdminLogin;
import PatientManagementSystem.Login.DoctorLogin;
import PatientManagementSystem.Login.Login;
import PatientManagementSystem.Login.PatientLogin;
import PatientManagementSystem.Login.SecretaryLogin;
import PatientManagementSystem.PatientFunctionality.CreateAccountRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Objects;

/**
 *
 * @author james
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        mainPanel = new javax.swing.JPanel();
        PnlLogin = new javax.swing.JPanel();
        BtnPatientAccount = new javax.swing.JButton();
        BtnLoginRequest = new javax.swing.JButton();
        TxtUsername = new javax.swing.JTextField();
        TxtPassword = new javax.swing.JTextField();
        LblLoginUsername = new javax.swing.JLabel();
        LblLoginPassword = new javax.swing.JLabel();
        CmbLoginAccountType = new javax.swing.JComboBox<>();
        LblLoginAccountTYpe = new javax.swing.JLabel();
        PnlRequestPatientAccount = new javax.swing.JPanel();
        TxtPotentialName = new javax.swing.JTextField();
        TxtPotentialAddress = new javax.swing.JTextField();
        CmbPotentialGender = new javax.swing.JComboBox<>();
        BtnPatientAccountRequest = new javax.swing.JButton();
        BtnBackToLogin = new javax.swing.JButton();
        LblPotentialName = new javax.swing.JLabel();
        LblPotentialAddress = new javax.swing.JLabel();
        LblPotentialPassword = new javax.swing.JLabel();
        LblPotentialGender = new javax.swing.JLabel();
        LblPotentialDoB = new javax.swing.JLabel();
        TxtPotentialPassword = new javax.swing.JTextField();
        TxtPotentialDoB = new javax.swing.JTextField();
        PnlAdminMainPage = new javax.swing.JPanel();
        LblAdminMainPage = new javax.swing.JLabel();
        BtnAdmCreateAccountPage = new javax.swing.JButton();
        BtnRemoveAccountPage = new javax.swing.JButton();
        btnViewRatingsPage = new javax.swing.JButton();
        BtnGenerateFeedbackPage = new javax.swing.JButton();
        CmbChooseDoctorForFeedback = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        PnlViewDoctorRatings = new javax.swing.JPanel();
        CmbChooseDoctorForRating = new javax.swing.JComboBox<>();
        LblRatedDoctorRating = new javax.swing.JLabel();
        LblRatedDoctorID = new javax.swing.JLabel();
        LblRatedDoctorName = new javax.swing.JLabel();
        BtnAdmBack3 = new javax.swing.JButton();
        PnlCreateAccount = new javax.swing.JPanel();
        LblAdmCreateAccountName = new javax.swing.JLabel();
        LblAdmCreateAccountPassword = new javax.swing.JLabel();
        LblAdmCreateAccountType = new javax.swing.JLabel();
        LblAdmCreateAccountAddress = new javax.swing.JLabel();
        TxtAdmCreateAccountName = new javax.swing.JTextField();
        TxtAdmCreateAccountPassword = new javax.swing.JTextField();
        TxtAdmCreateAccountAddress = new javax.swing.JTextField();
        CmbAdmCreateAccountType = new javax.swing.JComboBox<>();
        BtnAdmCreateAccount = new javax.swing.JButton();
        BtnAdmBack1 = new javax.swing.JButton();
        PnlRemoveAccounts = new javax.swing.JPanel();
        TxtAccountToBeRemoved = new javax.swing.JTextField();
        CmbToBeRemovedAccountType = new javax.swing.JComboBox<>();
        LblToBeRemovedID = new javax.swing.JLabel();
        LblToBeRemovedAccountType = new javax.swing.JLabel();
        BtnRemoveAccount = new javax.swing.JButton();
        BtnAdmBack2 = new javax.swing.JButton();
        PnlGenerateFeedback = new javax.swing.JPanel();
        BtnAdmBack4 = new javax.swing.JButton();
        LblFeedbackDoctorName = new javax.swing.JLabel();
        CmbSelectComment = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAreaFeedbackComment = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        LblFeedbackRating = new javax.swing.JLabel();
        PnlPatientMainPage = new javax.swing.JPanel();
        LblPatientMainPage = new javax.swing.JLabel();
        PnlRequestAppointment = new javax.swing.JPanel();
        PnlRateDoctors = new javax.swing.JPanel();
        PnlViewOwnHistory = new javax.swing.JPanel();
        PnlViewAppointment = new javax.swing.JPanel();
        PnlViewPrescription = new javax.swing.JPanel();
        PnlDoctorMainPage = new javax.swing.JPanel();
        LblDoctorMainPage = new javax.swing.JLabel();
        PnlWritePrescription = new javax.swing.JPanel();
        PnlCreateNewMedicine = new javax.swing.JPanel();
        PnlProposeAppointment = new javax.swing.JPanel();
        PnlViewAppointments = new javax.swing.JPanel();
        PnlMakeNotes = new javax.swing.JPanel();
        PnlSecretaryMainPage = new javax.swing.JPanel();
        LblSecretaryMainPage = new javax.swing.JLabel();
        PnlCreateAppointment = new javax.swing.JPanel();
        PnlMedicine = new javax.swing.JPanel();
        PnlPatientAccountRequesrs = new javax.swing.JPanel();
        PnlApproveRemovalRequest = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        BtnPatientAccount.setText("Request Patient Account");
        BtnPatientAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPatientAccountActionPerformed(evt);
            }
        });

        BtnLoginRequest.setText("Login");
        BtnLoginRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginRequestActionPerformed(evt);
            }
        });

        TxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPasswordActionPerformed(evt);
            }
        });

        LblLoginUsername.setText("Username");

        LblLoginPassword.setText("Password");

        CmbLoginAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patient", "Doctor", "Secretary", "Admin" }));

        LblLoginAccountTYpe.setText("Account Type");

        javax.swing.GroupLayout PnlLoginLayout = new javax.swing.GroupLayout(PnlLogin);
        PnlLogin.setLayout(PnlLoginLayout);
        PnlLoginLayout.setHorizontalGroup(
            PnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlLoginLayout.createSequentialGroup()
                .addGroup(PnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlLoginLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(BtnLoginRequest))
                    .addGroup(PnlLoginLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(PnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblLoginAccountTYpe)
                            .addGroup(PnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LblLoginUsername)
                                .addComponent(TxtUsername)
                                .addComponent(TxtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BtnPatientAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblLoginPassword)
                                .addComponent(CmbLoginAccountType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        PnlLoginLayout.setVerticalGroup(
            PnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlLoginLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(LblLoginUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblLoginPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblLoginAccountTYpe)
                .addGap(2, 2, 2)
                .addComponent(CmbLoginAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnLoginRequest)
                .addGap(18, 18, 18)
                .addComponent(BtnPatientAccount)
                .addGap(50, 50, 50))
        );

        mainPanel.add(PnlLogin, "PnlLogin");

        TxtPotentialName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPotentialNameActionPerformed(evt);
            }
        });

        CmbPotentialGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        BtnPatientAccountRequest.setText("Request Account");
        BtnPatientAccountRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPatientAccountRequestActionPerformed(evt);
            }
        });

        BtnBackToLogin.setText("back To Login");
        BtnBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackToLoginActionPerformed(evt);
            }
        });

        LblPotentialName.setText("Name");

        LblPotentialAddress.setText("Address");

        LblPotentialPassword.setText("Password");

        LblPotentialGender.setText("Gender");

        LblPotentialDoB.setText("Date Of Birth");

        javax.swing.GroupLayout PnlRequestPatientAccountLayout = new javax.swing.GroupLayout(PnlRequestPatientAccount);
        PnlRequestPatientAccount.setLayout(PnlRequestPatientAccountLayout);
        PnlRequestPatientAccountLayout.setHorizontalGroup(
            PnlRequestPatientAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRequestPatientAccountLayout.createSequentialGroup()
                .addGroup(PnlRequestPatientAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlRequestPatientAccountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnBackToLogin))
                    .addGroup(PnlRequestPatientAccountLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(PnlRequestPatientAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnPatientAccountRequest)
                            .addComponent(LblPotentialDoB)
                            .addComponent(LblPotentialName)
                            .addComponent(LblPotentialAddress)
                            .addComponent(LblPotentialPassword)
                            .addComponent(LblPotentialGender)
                            .addComponent(TxtPotentialName)
                            .addComponent(CmbPotentialGender, 0, 143, Short.MAX_VALUE)
                            .addComponent(TxtPotentialAddress)
                            .addComponent(TxtPotentialPassword)
                            .addComponent(TxtPotentialDoB))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        PnlRequestPatientAccountLayout.setVerticalGroup(
            PnlRequestPatientAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRequestPatientAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnBackToLogin)
                .addGap(61, 61, 61)
                .addComponent(LblPotentialName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPotentialName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(LblPotentialAddress)
                .addGap(2, 2, 2)
                .addComponent(TxtPotentialAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(LblPotentialPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPotentialPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblPotentialGender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(CmbPotentialGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblPotentialDoB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPotentialDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPatientAccountRequest)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        mainPanel.add(PnlRequestPatientAccount, "PnlRequestPatientAccount");

        LblAdminMainPage.setText("Admin Main Page");

        BtnAdmCreateAccountPage.setText("Create Account");
        BtnAdmCreateAccountPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdmCreateAccountPageActionPerformed(evt);
            }
        });

        BtnRemoveAccountPage.setText("Delete Account");
        BtnRemoveAccountPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoveAccountPageActionPerformed(evt);
            }
        });

        btnViewRatingsPage.setText("View Ratings");
        btnViewRatingsPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRatingsPageActionPerformed(evt);
            }
        });

        BtnGenerateFeedbackPage.setText("Generate Feedback");
        BtnGenerateFeedbackPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerateFeedbackPageActionPerformed(evt);
            }
        });

        jLabel4.setText("Choose Doctor For Report");

        javax.swing.GroupLayout PnlAdminMainPageLayout = new javax.swing.GroupLayout(PnlAdminMainPage);
        PnlAdminMainPage.setLayout(PnlAdminMainPageLayout);
        PnlAdminMainPageLayout.setHorizontalGroup(
            PnlAdminMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdminMainPageLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(PnlAdminMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(PnlAdminMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BtnGenerateFeedbackPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewRatingsPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnRemoveAccountPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAdmCreateAccountPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PnlAdminMainPageLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(LblAdminMainPage))
                        .addComponent(CmbChooseDoctorForFeedback, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        PnlAdminMainPageLayout.setVerticalGroup(
            PnlAdminMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdminMainPageLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(LblAdminMainPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAdmCreateAccountPage)
                .addGap(18, 18, 18)
                .addComponent(BtnRemoveAccountPage)
                .addGap(18, 18, 18)
                .addComponent(btnViewRatingsPage)
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmbChooseDoctorForFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnGenerateFeedbackPage)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        mainPanel.add(PnlAdminMainPage, "PnlAdminMainPage");

        CmbChooseDoctorForRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbChooseDoctorForRatingActionPerformed(evt);
            }
        });

        LblRatedDoctorID.setText("jLabel2");

        LblRatedDoctorName.setText("jLabel3");

        BtnAdmBack3.setText("Back To Admin Main Page");
        BtnAdmBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdmBack3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlViewDoctorRatingsLayout = new javax.swing.GroupLayout(PnlViewDoctorRatings);
        PnlViewDoctorRatings.setLayout(PnlViewDoctorRatingsLayout);
        PnlViewDoctorRatingsLayout.setHorizontalGroup(
            PnlViewDoctorRatingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlViewDoctorRatingsLayout.createSequentialGroup()
                .addGroup(PnlViewDoctorRatingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlViewDoctorRatingsLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(PnlViewDoctorRatingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblRatedDoctorName)
                            .addComponent(LblRatedDoctorID)
                            .addComponent(CmbChooseDoctorForRating, 0, 162, Short.MAX_VALUE)
                            .addComponent(LblRatedDoctorRating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PnlViewDoctorRatingsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAdmBack3)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        PnlViewDoctorRatingsLayout.setVerticalGroup(
            PnlViewDoctorRatingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlViewDoctorRatingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAdmBack3)
                .addGap(92, 92, 92)
                .addComponent(CmbChooseDoctorForRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblRatedDoctorID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblRatedDoctorName)
                .addGap(17, 17, 17)
                .addComponent(LblRatedDoctorRating)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        mainPanel.add(PnlViewDoctorRatings, "PnlViewDoctorRatings");

        LblAdmCreateAccountName.setText("Name ");

        LblAdmCreateAccountPassword.setText("Password");

        LblAdmCreateAccountType.setText("Account Type");

        LblAdmCreateAccountAddress.setText("Address");

        CmbAdmCreateAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Doctor", "Secretary" }));

        BtnAdmCreateAccount.setText("Create Account");
        BtnAdmCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdmCreateAccountActionPerformed(evt);
            }
        });

        BtnAdmBack1.setText("Back To Main Page");
        BtnAdmBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdmBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlCreateAccountLayout = new javax.swing.GroupLayout(PnlCreateAccount);
        PnlCreateAccount.setLayout(PnlCreateAccountLayout);
        PnlCreateAccountLayout.setHorizontalGroup(
            PnlCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCreateAccountLayout.createSequentialGroup()
                .addGroup(PnlCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlCreateAccountLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(PnlCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnAdmCreateAccount)
                            .addComponent(CmbAdmCreateAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LblAdmCreateAccountAddress)
                                .addComponent(LblAdmCreateAccountType)
                                .addComponent(LblAdmCreateAccountPassword)
                                .addComponent(LblAdmCreateAccountName)
                                .addComponent(TxtAdmCreateAccountName, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(TxtAdmCreateAccountPassword)
                                .addComponent(TxtAdmCreateAccountAddress))))
                    .addGroup(PnlCreateAccountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAdmBack1)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        PnlCreateAccountLayout.setVerticalGroup(
            PnlCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCreateAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAdmBack1)
                .addGap(56, 56, 56)
                .addComponent(LblAdmCreateAccountName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtAdmCreateAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(LblAdmCreateAccountPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtAdmCreateAccountPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblAdmCreateAccountAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtAdmCreateAccountAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblAdmCreateAccountType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmbAdmCreateAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAdmCreateAccount)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        mainPanel.add(PnlCreateAccount, "PnlCreateAccount");

        CmbToBeRemovedAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Secretary" }));

        LblToBeRemovedID.setText("Account ID");

        LblToBeRemovedAccountType.setText("Account Type");

        BtnRemoveAccount.setText("Remove Account");
        BtnRemoveAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoveAccountActionPerformed(evt);
            }
        });

        BtnAdmBack2.setText("Back To Main Page");
        BtnAdmBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdmBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlRemoveAccountsLayout = new javax.swing.GroupLayout(PnlRemoveAccounts);
        PnlRemoveAccounts.setLayout(PnlRemoveAccountsLayout);
        PnlRemoveAccountsLayout.setHorizontalGroup(
            PnlRemoveAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRemoveAccountsLayout.createSequentialGroup()
                .addGroup(PnlRemoveAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlRemoveAccountsLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(PnlRemoveAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblToBeRemovedAccountType)
                            .addComponent(LblToBeRemovedID)
                            .addComponent(TxtAccountToBeRemoved)
                            .addComponent(CmbToBeRemovedAccountType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnRemoveAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                    .addGroup(PnlRemoveAccountsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAdmBack2)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        PnlRemoveAccountsLayout.setVerticalGroup(
            PnlRemoveAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRemoveAccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAdmBack2)
                .addGap(81, 81, 81)
                .addComponent(LblToBeRemovedID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtAccountToBeRemoved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblToBeRemovedAccountType)
                .addGap(3, 3, 3)
                .addComponent(CmbToBeRemovedAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnRemoveAccount)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        mainPanel.add(PnlRemoveAccounts, "PnlRemoveAccounts");

        BtnAdmBack4.setText("Back to Admin Main Page");
        BtnAdmBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdmBack4ActionPerformed(evt);
            }
        });

        LblFeedbackDoctorName.setText("jLabel1");

        CmbSelectComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbSelectCommentActionPerformed(evt);
            }
        });

        TxtAreaFeedbackComment.setEditable(false);
        TxtAreaFeedbackComment.setColumns(20);
        TxtAreaFeedbackComment.setRows(5);
        jScrollPane2.setViewportView(TxtAreaFeedbackComment);

        jLabel2.setText("Rating");

        LblFeedbackRating.setText("jLabel3");

        javax.swing.GroupLayout PnlGenerateFeedbackLayout = new javax.swing.GroupLayout(PnlGenerateFeedback);
        PnlGenerateFeedback.setLayout(PnlGenerateFeedbackLayout);
        PnlGenerateFeedbackLayout.setHorizontalGroup(
            PnlGenerateFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlGenerateFeedbackLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlGenerateFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAdmBack4)
                    .addComponent(LblFeedbackDoctorName)
                    .addComponent(CmbSelectComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(LblFeedbackRating))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        PnlGenerateFeedbackLayout.setVerticalGroup(
            PnlGenerateFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlGenerateFeedbackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAdmBack4)
                .addGap(18, 18, 18)
                .addComponent(LblFeedbackDoctorName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmbSelectComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblFeedbackRating)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        mainPanel.add(PnlGenerateFeedback, "PnlGenerateFeedback");

        LblPatientMainPage.setText("Patient Main Page");

        javax.swing.GroupLayout PnlPatientMainPageLayout = new javax.swing.GroupLayout(PnlPatientMainPage);
        PnlPatientMainPage.setLayout(PnlPatientMainPageLayout);
        PnlPatientMainPageLayout.setHorizontalGroup(
            PnlPatientMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlPatientMainPageLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(LblPatientMainPage)
                .addGap(209, 209, 209))
        );
        PnlPatientMainPageLayout.setVerticalGroup(
            PnlPatientMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPatientMainPageLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(LblPatientMainPage)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        mainPanel.add(PnlPatientMainPage, "PnlPatientMainPage");

        javax.swing.GroupLayout PnlRequestAppointmentLayout = new javax.swing.GroupLayout(PnlRequestAppointment);
        PnlRequestAppointment.setLayout(PnlRequestAppointmentLayout);
        PnlRequestAppointmentLayout.setHorizontalGroup(
            PnlRequestAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        PnlRequestAppointmentLayout.setVerticalGroup(
            PnlRequestAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(PnlRequestAppointment, "PnlRequestAppointment");

        javax.swing.GroupLayout PnlRateDoctorsLayout = new javax.swing.GroupLayout(PnlRateDoctors);
        PnlRateDoctors.setLayout(PnlRateDoctorsLayout);
        PnlRateDoctorsLayout.setHorizontalGroup(
            PnlRateDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        PnlRateDoctorsLayout.setVerticalGroup(
            PnlRateDoctorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(PnlRateDoctors, "PnlRateDoctors");

        javax.swing.GroupLayout PnlViewOwnHistoryLayout = new javax.swing.GroupLayout(PnlViewOwnHistory);
        PnlViewOwnHistory.setLayout(PnlViewOwnHistoryLayout);
        PnlViewOwnHistoryLayout.setHorizontalGroup(
            PnlViewOwnHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        PnlViewOwnHistoryLayout.setVerticalGroup(
            PnlViewOwnHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(PnlViewOwnHistory, "PnlViewOwnHistory");

        javax.swing.GroupLayout PnlViewAppointmentLayout = new javax.swing.GroupLayout(PnlViewAppointment);
        PnlViewAppointment.setLayout(PnlViewAppointmentLayout);
        PnlViewAppointmentLayout.setHorizontalGroup(
            PnlViewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        PnlViewAppointmentLayout.setVerticalGroup(
            PnlViewAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(PnlViewAppointment, "PnlViewAppointment");

        javax.swing.GroupLayout PnlViewPrescriptionLayout = new javax.swing.GroupLayout(PnlViewPrescription);
        PnlViewPrescription.setLayout(PnlViewPrescriptionLayout);
        PnlViewPrescriptionLayout.setHorizontalGroup(
            PnlViewPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        PnlViewPrescriptionLayout.setVerticalGroup(
            PnlViewPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(PnlViewPrescription, "PnlViewPrescription");

        LblDoctorMainPage.setText("Doctor Main Page");

        javax.swing.GroupLayout PnlDoctorMainPageLayout = new javax.swing.GroupLayout(PnlDoctorMainPage);
        PnlDoctorMainPage.setLayout(PnlDoctorMainPageLayout);
        PnlDoctorMainPageLayout.setHorizontalGroup(
            PnlDoctorMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDoctorMainPageLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(LblDoctorMainPage)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        PnlDoctorMainPageLayout.setVerticalGroup(
            PnlDoctorMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDoctorMainPageLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(LblDoctorMainPage)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        mainPanel.add(PnlDoctorMainPage, "PnlDoctorMainPage");

        javax.swing.GroupLayout PnlWritePrescriptionLayout = new javax.swing.GroupLayout(PnlWritePrescription);
        PnlWritePrescription.setLayout(PnlWritePrescriptionLayout);
        PnlWritePrescriptionLayout.setHorizontalGroup(
            PnlWritePrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        PnlWritePrescriptionLayout.setVerticalGroup(
            PnlWritePrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(PnlWritePrescription, "PnlWritePrescription");

        javax.swing.GroupLayout PnlCreateNewMedicineLayout = new javax.swing.GroupLayout(PnlCreateNewMedicine);
        PnlCreateNewMedicine.setLayout(PnlCreateNewMedicineLayout);
        PnlCreateNewMedicineLayout.setHorizontalGroup(
            PnlCreateNewMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        PnlCreateNewMedicineLayout.setVerticalGroup(
            PnlCreateNewMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(PnlCreateNewMedicine, "PnlCreateNewMedicine");

        javax.swing.GroupLayout PnlProposeAppointmentLayout = new javax.swing.GroupLayout(PnlProposeAppointment);
        PnlProposeAppointment.setLayout(PnlProposeAppointmentLayout);
        PnlProposeAppointmentLayout.setHorizontalGroup(
            PnlProposeAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PnlProposeAppointmentLayout.setVerticalGroup(
            PnlProposeAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainPanel.add(PnlProposeAppointment, "PnlProposeAppointment");

        javax.swing.GroupLayout PnlViewAppointmentsLayout = new javax.swing.GroupLayout(PnlViewAppointments);
        PnlViewAppointments.setLayout(PnlViewAppointmentsLayout);
        PnlViewAppointmentsLayout.setHorizontalGroup(
            PnlViewAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        PnlViewAppointmentsLayout.setVerticalGroup(
            PnlViewAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(PnlViewAppointments, "PnlViewAppointments");

        javax.swing.GroupLayout PnlMakeNotesLayout = new javax.swing.GroupLayout(PnlMakeNotes);
        PnlMakeNotes.setLayout(PnlMakeNotesLayout);
        PnlMakeNotesLayout.setHorizontalGroup(
            PnlMakeNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        PnlMakeNotesLayout.setVerticalGroup(
            PnlMakeNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(PnlMakeNotes, "PnlMakeNotes");

        LblSecretaryMainPage.setText("Secretary Main Page");

        javax.swing.GroupLayout PnlSecretaryMainPageLayout = new javax.swing.GroupLayout(PnlSecretaryMainPage);
        PnlSecretaryMainPage.setLayout(PnlSecretaryMainPageLayout);
        PnlSecretaryMainPageLayout.setHorizontalGroup(
            PnlSecretaryMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSecretaryMainPageLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(LblSecretaryMainPage)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        PnlSecretaryMainPageLayout.setVerticalGroup(
            PnlSecretaryMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSecretaryMainPageLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(LblSecretaryMainPage)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        mainPanel.add(PnlSecretaryMainPage, "PnlSecretaryMainPage");

        javax.swing.GroupLayout PnlCreateAppointmentLayout = new javax.swing.GroupLayout(PnlCreateAppointment);
        PnlCreateAppointment.setLayout(PnlCreateAppointmentLayout);
        PnlCreateAppointmentLayout.setHorizontalGroup(
            PnlCreateAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        PnlCreateAppointmentLayout.setVerticalGroup(
            PnlCreateAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(PnlCreateAppointment, "PnlCreateAppointment");

        javax.swing.GroupLayout PnlMedicineLayout = new javax.swing.GroupLayout(PnlMedicine);
        PnlMedicine.setLayout(PnlMedicineLayout);
        PnlMedicineLayout.setHorizontalGroup(
            PnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        PnlMedicineLayout.setVerticalGroup(
            PnlMedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(PnlMedicine, "PnlMedicine");

        javax.swing.GroupLayout PnlPatientAccountRequesrsLayout = new javax.swing.GroupLayout(PnlPatientAccountRequesrs);
        PnlPatientAccountRequesrs.setLayout(PnlPatientAccountRequesrsLayout);
        PnlPatientAccountRequesrsLayout.setHorizontalGroup(
            PnlPatientAccountRequesrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        PnlPatientAccountRequesrsLayout.setVerticalGroup(
            PnlPatientAccountRequesrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(PnlPatientAccountRequesrs, "PnlPatientAccountRequest");

        javax.swing.GroupLayout PnlApproveRemovalRequestLayout = new javax.swing.GroupLayout(PnlApproveRemovalRequest);
        PnlApproveRemovalRequest.setLayout(PnlApproveRemovalRequestLayout);
        PnlApproveRemovalRequestLayout.setHorizontalGroup(
            PnlApproveRemovalRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        PnlApproveRemovalRequestLayout.setVerticalGroup(
            PnlApproveRemovalRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(PnlApproveRemovalRequest, "PnlApproveRemovalRequests");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPatientAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPatientAccountActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "PnlRequestPatientAccount");
    }//GEN-LAST:event_BtnPatientAccountActionPerformed

    private void BtnLoginRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginRequestActionPerformed
        Login login;
        switch(CmbLoginAccountType.getSelectedItem().toString()){
            case "Patient":
                login = new PatientLogin();
                if (login.AttemptLogin(TxtPassword.getText(), TxtUsername.getText()) == true) {
                    CardLayout card = (CardLayout)mainPanel.getLayout();
                    card.show(mainPanel, "PnlPatientMainPage");
                }   
                break;
            case "Doctor":
                login = new DoctorLogin();
                if (login.AttemptLogin(TxtPassword.getText(), TxtUsername.getText()) == true) {
                    CardLayout card = (CardLayout)mainPanel.getLayout();
                    card.show(mainPanel, "PnlDoctorMainPage");
                }   
                break;
            case "Admin":
                login = new AdminLogin();
                if (login.AttemptLogin(TxtPassword.getText(), TxtUsername.getText()) == true) {
                    CardLayout card = (CardLayout)mainPanel.getLayout();
                    card.show(mainPanel, "PnlAdminMainPage");
                    Admin admin = new Admin();
                    ArrayList<Object> Ratings  = admin.GetDoctorRatings();
                    for (int i = 0; i < Ratings.size()/3; i++) {
                        String DoctorID = Ratings.get(i*3+1).toString();
                        CmbChooseDoctorForFeedback.addItem(DoctorID);
                    }
                }   
                break;
            case "Secretary":
                login = new SecretaryLogin();
                if (login.AttemptLogin(TxtPassword.getText(), TxtUsername.getText()) == true) {
                    CardLayout card = (CardLayout)mainPanel.getLayout();
                    card.show(mainPanel, "PnlSecretaryMainPage");
                }   
                break;
        }    
        TxtPassword.setText("");
        TxtUsername.setText("");
    }//GEN-LAST:event_BtnLoginRequestActionPerformed

    private void BtnBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackToLoginActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "PnlLogin");
    }//GEN-LAST:event_BtnBackToLoginActionPerformed

    private void BtnPatientAccountRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPatientAccountRequestActionPerformed
        CreateAccountRequest accountRequest = new CreateAccountRequest();
        String gender = CmbPotentialGender.getSelectedItem().toString();
        int Gender = 0;
        switch(gender){
            case "Male":
                Gender = 1;
                break;
            case "Female":
                Gender = 2;
                break;
            case "Other":
                Gender = 3;
                break;
        }
        String DoB = TxtPotentialDoB.getText();
        accountRequest.CreateNewAccountRequest(TxtPotentialName.getText(), TxtPotentialAddress.getText(), TxtPotentialPassword.getText(), Gender, TxtPotentialDoB.getText());
        TxtPotentialName.setText("");
        TxtPotentialAddress.setText("");
        TxtPotentialPassword.setText("");
        TxtPotentialDoB.setText("");
    }//GEN-LAST:event_BtnPatientAccountRequestActionPerformed

    private void TxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPasswordActionPerformed

    private void TxtPotentialNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPotentialNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPotentialNameActionPerformed

    private void BtnAdmBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdmBack1ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "PnlAdminMainPage");
    }//GEN-LAST:event_BtnAdmBack1ActionPerformed

    private void BtnAdmCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdmCreateAccountActionPerformed
        Admin admin = new Admin();
        admin.CreateAccount(CmbAdmCreateAccountType.getSelectedItem().toString(), TxtAdmCreateAccountPassword.getText(), TxtAdmCreateAccountName.getText(), TxtAdmCreateAccountAddress.getText());
        TxtAdmCreateAccountName.setText("");
        TxtAdmCreateAccountAddress.setText("");
        TxtAdmCreateAccountPassword.setText("");
    }//GEN-LAST:event_BtnAdmCreateAccountActionPerformed

    private void BtnAdmCreateAccountPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdmCreateAccountPageActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "PnlCreateAccount");
    }//GEN-LAST:event_BtnAdmCreateAccountPageActionPerformed

    private void BtnAdmBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdmBack2ActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "PnlAdminMainPage");
    }//GEN-LAST:event_BtnAdmBack2ActionPerformed

    private void BtnRemoveAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoveAccountActionPerformed
        Admin admin = new Admin();
        admin.RemoveAccount(CmbToBeRemovedAccountType.getSelectedItem().toString(), TxtAccountToBeRemoved.getText());
        TxtAccountToBeRemoved.setText("");
    }//GEN-LAST:event_BtnRemoveAccountActionPerformed

    private void BtnRemoveAccountPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoveAccountPageActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "PnlRemoveAccounts");
    }//GEN-LAST:event_BtnRemoveAccountPageActionPerformed

    private void BtnAdmBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdmBack3ActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "PnlAdminMainPage");
    }//GEN-LAST:event_BtnAdmBack3ActionPerformed

    private void btnViewRatingsPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRatingsPageActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "PnlViewDoctorRatings");
        Admin admin = new Admin();
        ArrayList<Object> Ratings  = admin.GetDoctorRatings();
        for (int i = 0; i < Ratings.size()/3; i++) {
            String DoctorID = Ratings.get(i*3+1).toString();
            CmbChooseDoctorForRating.addItem(DoctorID);
        }
        LblRatedDoctorName.setText(Ratings.get(0).toString());
        LblRatedDoctorID.setText(Ratings.get(1).toString());
        LblRatedDoctorRating.setText(Ratings.get(2).toString());
    }//GEN-LAST:event_btnViewRatingsPageActionPerformed

    private void BtnGenerateFeedbackPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerateFeedbackPageActionPerformed
        CmbSelectComment.removeAllItems();
        TxtAreaFeedbackComment.setText("");
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "PnlGenerateFeedback");
        Admin admin = new Admin();
        ArrayList<Object> FeedbackReport = admin.GenerateFeedbackReport(CmbChooseDoctorForFeedback.getSelectedItem().toString());
        LblFeedbackDoctorName.setText(CmbChooseDoctorForFeedback.getSelectedItem().toString());
        for (int i = 1; i < FeedbackReport.size()-1; i++) {
            CmbSelectComment.addItem("Comment " + i);
        }
        TxtAreaFeedbackComment.setText(FeedbackReport.get(1).toString());
        String rating = FeedbackReport.get(FeedbackReport.size()-1).toString();
        if (!rating.equals("-1")) {
            LblFeedbackRating.setText(rating);
        }
        else{
            LblFeedbackRating.setText("Doctor Not Yet Rated");
        }               
    }//GEN-LAST:event_BtnGenerateFeedbackPageActionPerformed

    private void BtnAdmBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdmBack4ActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "PnlAdminMainPage");
    }//GEN-LAST:event_BtnAdmBack4ActionPerformed

    private void CmbSelectCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbSelectCommentActionPerformed
        Admin admin = new Admin();
        ArrayList<Object> FeedbackReport = admin.GenerateFeedbackReport(CmbChooseDoctorForFeedback.getSelectedItem().toString());
        int Comment = CmbSelectComment.getSelectedIndex();
        TxtAreaFeedbackComment.setText(FeedbackReport.get(Comment + 1).toString());
    }//GEN-LAST:event_CmbSelectCommentActionPerformed

    private void CmbChooseDoctorForRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbChooseDoctorForRatingActionPerformed
       Admin admin = new Admin();
       ArrayList<Object> Ratings  = admin.GetDoctorRatings();
       int Doctor = CmbChooseDoctorForRating.getSelectedIndex() * 3;
       LblRatedDoctorName.setText(Ratings.get(Doctor).toString());
       LblRatedDoctorID.setText(Ratings.get(Doctor+1).toString());
        if (!Ratings.get(Doctor+2).toString().equals("-1")) {
            LblRatedDoctorRating.setText(Ratings.get(Doctor+2).toString());
        }
        else{
            LblRatedDoctorRating.setText("Doctor Not Yet Rated");
        }       
    }//GEN-LAST:event_CmbChooseDoctorForRatingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdmBack1;
    private javax.swing.JButton BtnAdmBack2;
    private javax.swing.JButton BtnAdmBack3;
    private javax.swing.JButton BtnAdmBack4;
    private javax.swing.JButton BtnAdmCreateAccount;
    private javax.swing.JButton BtnAdmCreateAccountPage;
    private javax.swing.JButton BtnBackToLogin;
    private javax.swing.JButton BtnGenerateFeedbackPage;
    private javax.swing.JButton BtnLoginRequest;
    private javax.swing.JButton BtnPatientAccount;
    private javax.swing.JButton BtnPatientAccountRequest;
    private javax.swing.JButton BtnRemoveAccount;
    private javax.swing.JButton BtnRemoveAccountPage;
    private javax.swing.JComboBox<String> CmbAdmCreateAccountType;
    private javax.swing.JComboBox<String> CmbChooseDoctorForFeedback;
    private javax.swing.JComboBox<String> CmbChooseDoctorForRating;
    private javax.swing.JComboBox<String> CmbLoginAccountType;
    private javax.swing.JComboBox<String> CmbPotentialGender;
    private javax.swing.JComboBox<String> CmbSelectComment;
    private javax.swing.JComboBox<String> CmbToBeRemovedAccountType;
    private javax.swing.JLabel LblAdmCreateAccountAddress;
    private javax.swing.JLabel LblAdmCreateAccountName;
    private javax.swing.JLabel LblAdmCreateAccountPassword;
    private javax.swing.JLabel LblAdmCreateAccountType;
    private javax.swing.JLabel LblAdminMainPage;
    private javax.swing.JLabel LblDoctorMainPage;
    private javax.swing.JLabel LblFeedbackDoctorName;
    private javax.swing.JLabel LblFeedbackRating;
    private javax.swing.JLabel LblLoginAccountTYpe;
    private javax.swing.JLabel LblLoginPassword;
    private javax.swing.JLabel LblLoginUsername;
    private javax.swing.JLabel LblPatientMainPage;
    private javax.swing.JLabel LblPotentialAddress;
    private javax.swing.JLabel LblPotentialDoB;
    private javax.swing.JLabel LblPotentialGender;
    private javax.swing.JLabel LblPotentialName;
    private javax.swing.JLabel LblPotentialPassword;
    private javax.swing.JLabel LblRatedDoctorID;
    private javax.swing.JLabel LblRatedDoctorName;
    private javax.swing.JLabel LblRatedDoctorRating;
    private javax.swing.JLabel LblSecretaryMainPage;
    private javax.swing.JLabel LblToBeRemovedAccountType;
    private javax.swing.JLabel LblToBeRemovedID;
    private javax.swing.JPanel PnlAdminMainPage;
    private javax.swing.JPanel PnlApproveRemovalRequest;
    private javax.swing.JPanel PnlCreateAccount;
    private javax.swing.JPanel PnlCreateAppointment;
    private javax.swing.JPanel PnlCreateNewMedicine;
    private javax.swing.JPanel PnlDoctorMainPage;
    private javax.swing.JPanel PnlGenerateFeedback;
    private javax.swing.JPanel PnlLogin;
    private javax.swing.JPanel PnlMakeNotes;
    private javax.swing.JPanel PnlMedicine;
    private javax.swing.JPanel PnlPatientAccountRequesrs;
    private javax.swing.JPanel PnlPatientMainPage;
    private javax.swing.JPanel PnlProposeAppointment;
    private javax.swing.JPanel PnlRateDoctors;
    private javax.swing.JPanel PnlRemoveAccounts;
    private javax.swing.JPanel PnlRequestAppointment;
    private javax.swing.JPanel PnlRequestPatientAccount;
    private javax.swing.JPanel PnlSecretaryMainPage;
    private javax.swing.JPanel PnlViewAppointment;
    private javax.swing.JPanel PnlViewAppointments;
    private javax.swing.JPanel PnlViewDoctorRatings;
    private javax.swing.JPanel PnlViewOwnHistory;
    private javax.swing.JPanel PnlViewPrescription;
    private javax.swing.JPanel PnlWritePrescription;
    private javax.swing.JTextField TxtAccountToBeRemoved;
    private javax.swing.JTextField TxtAdmCreateAccountAddress;
    private javax.swing.JTextField TxtAdmCreateAccountName;
    private javax.swing.JTextField TxtAdmCreateAccountPassword;
    private javax.swing.JTextArea TxtAreaFeedbackComment;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JTextField TxtPotentialAddress;
    private javax.swing.JTextField TxtPotentialDoB;
    private javax.swing.JTextField TxtPotentialName;
    private javax.swing.JTextField TxtPotentialPassword;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JButton btnViewRatingsPage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
